name: Build Images

on:
  push:
    tags:
      - "tRackIT-OS-*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          submodules: recursive
          token: ${{ secrets.PAT_JONASHOECHST }}

      - name: Run Base.Pifile
        uses: Nature40/pimod@v0.6.0
        with:
          pifile: Base.Pifile
      - name: Run tRackIT-OS.Pifile
        uses: Nature40/pimod@v0.6.0
        with:
          pifile: tRackIT-OS.Pifile

      - name: Set Release Version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Rename tRackIT-OS.img
        run: mv tRackIT-OS.img ${{ env.RELEASE_VERSION }}.img
      - name: Package ${{ env.RELEASE_VERSION }}.zip
        run: zip ${{ env.RELEASE_VERSION }}.zip ${{ env.RELEASE_VERSION }}.img
      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: true
      - name: Upload ${{ env.RELEASE_VERSION }}.zip to release
        id: upload_trackit_os_zip
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.RELEASE_VERSION }}.zip
          asset_name: ${{ env.RELEASE_VERSION }}.zip
          asset_content_type: application/zip
